export const members = [
  { fullName: "Omotomiwa Afonja", username: "S.F Tommy" },
  { fullName: "Owai Owai", username: "thisOx2" },
  { fullName: "Ummi M Kallay", username: "Khay" },
  { fullName: "Peace Ihendi", username: "Pearl" },
  { fullName: "Soneye Abimbola", username: "The Product Girlie" },
  { fullName: "Folajomi Bello", username: "Magafox" },
  { fullName: "Emmanuel Bassey Esoh", username: "Emmanuel Young" },
  { fullName: "Ayodeji Adeniyi", username: "Dayjigud" },
  { fullName: "Favour Daniel", username: "MR.FÃVY" },
  { fullName: "Mercy Bamijoko", username: "Bambam" },
  { fullName: "Egeonu Chiamaka Happiness", username: "happiness egeonu" },
  { fullName: "Faith Obi", username: "Faith Obi" },
  { fullName: "Abiodun Adeleke", username: "Tearsmith" },
  { fullName: "Naomi Okoro", username: "Nayohmee" },
  { fullName: "Ugonwa Ohagwasi", username: "nwa" },
  { fullName: "Raphael Okeke", username: "@roktech" },
  { fullName: "Emmanuel Umeogu", username: "Emmalaka" },
  { fullName: "Paschal Obiorah", username: "Maazi" },
  { fullName: "Opeyemi Folorunsho", username: "Pleasure" },
  { fullName: "Murewa Raji", username: "Murewa Raji" },
  { fullName: "Pearl Akpaka", username: "PearlAkpaka" },
  { fullName: "Onyedikachi Oluchi", username: "Jemi" },
  { fullName: "Stephen Okoro", username: "venson" },
  { fullName: "Quell", username: "Quell" },
  { fullName: "Ndifreke Samuel", username: "Freksam" },
  { fullName: "Oke kolawole sunday", username: "Zeus" },
  { fullName: "Ofure Asotie", username: "FuureSama" },
  { fullName: "Ubah Delight Okechukwu", username: "DOUG" },
  { fullName: "Helen Efebe", username: "HelenGift" },
];
